# Generated by Django 4.1.6 on 2023-02-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentreply",
            name="post_id",
            field=models.ForeignKey(
                default="", on_delete=django.db.models.deletion.CASCADE, to="base.post"
            ),
            preserve_default=False,
        ),
    ]
