# Generated by Django 4.1.6 on 2023-02-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="base.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(default=""),
        ),
    ]
