# Generated by Django 4.1.6 on 2023-02-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_comment_post_id_alter_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentreply",
            name="comment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_reply",
                to="base.comment",
            ),
        ),
    ]
